language: cpp
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get install -qq freeglut3-dev libxpm-dev libgtk2.0-dev
script:
  - cmake . && make && ./ndkmol --version
  - cmake -D USE_ES2=1 . && make && ./ndkmol --version
branches:
  only:
    - master
notifications:
  recipients:
    - wojdyr@gmail.com
  email:
    on_success: change
    on_failure: always
